controller_list:
  - name: arm_1/gripper_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - gripper_finger_joint_l
      - gripper_finger_joint_r
